# Generated by Django 4.1.7 on 2023-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('decription', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.CharField(max_length=500)),
                ('applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('job_type', models.CharField(choices=[('fulltime', 'Fulltime'), ('partime', 'Partime'), ('remote', 'Remote'), ('freelance', 'Freelance')], default='fulltime', max_length=20)),
                ('search_by_date', models.CharField(choices=[('any', 'Any'), ('today', 'Today'), ('last 2 days', 'Last 2 days'), ('last 3 days', 'Last 3 days'), ('last 5 days', 'Last 5 days'), ('last 10 days', 'Last 10 days')], default='any', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
