# Generated by Django 4.1.7 on 2023-07-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_job_vacancy_country_job_vacancy_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_vacancy',
            name='go_live',
            field=models.BooleanField(choices=[(True, 'publish'), (False, 'unpublish')], default=False),
        ),
    ]
