# Generated by Django 4.2.4 on 2023-10-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderproduct_variation_orderproduct_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_tracking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
