# Generated by Django 4.2.4 on 2023-10-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
    ]
